[package]
name = "scylladb"
version = "2.0.0"
edition = "2021"

[lib]
name = "scylladb"
crate-type = ["lib", "cdylib"]

[dependencies]
phper = { version = "0.12" }

[dev-dependencies]
phper-test = { version = "0.12" }

[build-dependencies]
phper-build = { version = "0.12" }
