name: 'Docker Test Image'

on:
  workflow_dispatch:
    inputs:
      php:
        description: 'PHP Version'
        required: true
      zts:
        description: 'ZTS (Zend Thread Safety)'
        required: true
  workflow_call:
    inputs:
      php:
        type: string
        description: 'PHP Version'
        required: true
      zts:
        type: string
        description: 'ZTS (Zend Thread Safety)'
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push API
        id: docker_build_zts
        uses: docker/build-push-action@v4
        if: ${{ inputs.zts == 'yes' }}
        with:
          file: Dockerfile
          context: .
          push: true
          pull: true
          platforms: linux/amd64
          target: base
          tags: malusevd99/scylladb-php-driver:php-${{ inputs.php }}-zts
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php }}
            PHP_ZTS=${{ inputs.zts }}
            PHP_DEBUG="yes"
      - name: Build and push API
        id: docker_build_nts
        uses: docker/build-push-action@v4
        if: ${{ inputs.zts == 'no' }}
        with:
          file: Dockerfile
          context: .
          push: true
          pull: true
          platforms: linux/amd64
          target: base
          tags: malusevd99/scylladb-php-driver:php-${{ inputs.php }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ inputs.php }}
            PHP_ZTS=${{ inputs.zts }}
            PHP_DEBUG="yes"
