name: "Release"

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1.3
        id: version_tag
        with:
          tagRegex: "v(.*)"
  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          make_latest: true
          name: "v${{  needs.tag.outputs.version  }}"
          tag_name: "v${{  needs.tag.outputs.version }}"
          generate_release_notes: true
          append_body: true
          prerelease: false
          fail_on_unmatched_files: true
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: true
          releaseUrl: ${{ steps.release.outputs.url }}
          issues: true
          pullRequests: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CHANGELOG.md"
          branch: v1.3.x
          commit_options: '--no-verify --signoff'
          file_pattern: CHANGELOG.md
