name: 'Test PHP Extension'

on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: 'Image Tag'
        required: true
        default: 'php-8.2.6'
  workflow_call:
    inputs:
      image:
        type: string
        description: 'Image Tag'
        required: true
        default: 'php-8.2.6'
jobs:
  test:
    runs-on: ubuntu-latest
    container: malusevd99/scylladb-php-driver:${{ inputs.image }}
    services:
      scylladb:
        image: scylladb/scylla:5.1
        ports:
          - 9042:9042
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set new PATH
        run: |
          export PATH=$PATH:/usr/local/bin:/root/php/bin
          export LD_LIBRARY_PATH="/lib/x86_64-linux-gnu:/usr/local/lib/:/usr/lib:/lib:/usr/local/lib/x86_64-linux-gnu"
      - name: Compile using CMake
        run: |
          ./scripts/compile-extension.sh
      - name: Composer install
        working-directory: ./tests
        run: |
          /root/php/bin/php /bin/composer install
      - name: Run tests
        working-directory: ./tests
        run: |
          /root/php/bin/php ./vendor/bin/pest
        env:
          SCYLLADB_HOSTS: scylladb
          SCYLLADB_PORT: 9042
          SCYLLADB_USERNAME: cassandra
          SCYLLADB_PASSWORD: cassandra