name: 'Tests'

on:
  push:
    branches:
      - v1.3.x
  pull_request:
    branches:
      - v1.3.x
jobs:
  test_php81:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.1.21
  test_php81_zts:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.1.21-zts
  test_php82:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.2.8
  test_php82_zts:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.2.8-zts
  test_php83:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.3.0
  test_php83_zts:
    uses: he4rt/scylladb-php-driver/.github/workflows/test.yml@v1.3.x
    with:
      image: php-8.3.0
