name: 'Test PHP Extension'

on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: 'Image Tag'
        required: true
  workflow_call:
    inputs:
      image:
        type: string
        description: 'Image Tag'
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    container: malusevd99/scylladb-php-driver:php-${{ inputs.image }}
    services:
      scylladb:
        image: scylladb/scylla
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Run tests
        working-directory: ./tests
        run: |
          export PATH="$PATH:/usr/local/bin:/root/php/bin"
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu:/usr/local/lib/:/usr/lib:/lib:/usr/local/lib/x86_64-linux-gnu"
          ./scripts/compile-extension.sh
          /root/php/bin/php /bin/composer install
          /root/php/bin/php ./vendor/bin/pest
        env:
          SCYLLADB_HOSTS: scylladb
          SCYLLADB_PORT: 9042
          SCYLLADB_USERNAME: cassandra
          SCYLLADB_PASSWORD: cassandra